apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: exchange-main-worker
    newName: registry.digitalocean.com/camelot-labs/exchange-main-worker
    newTag: c9eaef5
  - name: incentives-events-ws-worker
    newName: registry.digitalocean.com/camelot-labs/incentives-events-ws-worker
    newTag: 01cb3ea
  - name: incentives-main-worker
    newName: registry.digitalocean.com/camelot-labs/incentives-main-worker
    newTag: 2a1dfb1
